site_name: Proton-docs
theme: readthedocs
repo_url: https://github.com/SugarLam1207/Proton-docs-template

nav:
  - Home:
    - Index: index.md
  - Hardware Guide:
    - Hardware Checklist: hardwarelist.md
    - Server Setup: serversetup.md
    - Tentacle Setup: networkenvsetup.md
    - One click Deployment: oneclickdeployment.md
    - Verify: oneclickdeployment.md
  - System Guide:
    - Quick start: quickstart.md
    - Order Management: ordermanagement.md
    - Other Order Types: otherordertypes.md
    - Payment Function: paymentfunction.md
    - Third-party Orders: thirdpartyorders.md
    - Report Center: reportcenter.md
    - Offline Mode: offlinemode.md
  - FAQ:
    - Common Issues: commonissues.md
    - Troubleshooting: troubleshooting.md
  - Contact Us:
    - Technical Support: technicalsupport.md
    - Feedback: feedback.md
